ENV['PATH'] = ENV['PATH'] + ';C:\Bitnami\redmine-3.2.3-0/git/bin'
ENV['PATH'] = ENV['PATH'] + ';C:\Bitnami\redmine-3.2.3-0/subversion/bin'
ENV['PATH'] = ENV['PATH'] + ';C:\Bitnami\redmine-3.2.3-0\imagemagick'
ENV['MAGICK_CODER_MODULE_PATH'] = 'C:\Bitnami\REDMIN~1.3-0\IMAGEM~1\modules\coders'
ENV['PATH'] = ENV['PATH'] + ';C:\Bitnami\redmine-3.2.3-0\ruby\bin'
